inherit_gem:
  bixby: bixby_default.yml

AllCops:
  Exclude:
    - bin/*
    - db/**/*
    - spec/fixtures/**/*
    - vendor/**/*
  TargetRubyVersion: 2.7

Metrics/AbcSize:
  Exclude:
    - app/controllers/spotlight/pages_controller.rb
    - app/controllers/tufts/tdl_resources_controller.rb
    - app/models/search_builder.rb
    - lib/tufts/hostname_fixer.rb
Metrics/BlockLength:
  Exclude: 
    - app/controllers/catalog_controller.rb
    - config/**/*
    - lib/tasks/data_cleaner.rake
    - lib/tasks/reindexer.rake
    - spec/features/feature_page_customizations_spec.rb
    - spec/features/sir_trevor_customizations_spec.rb
    - spec/features/tdl_ingest_spec.rb
    - spec/features/view_customizations_spec.rb
    - Guardfile
Metrics/CyclomaticComplexity:
  Exclude:
    - lib/tufts/hostname_fixer.rb
Metrics/PerceivedComplexity:
  Exclude:
    - lib/tufts/hostname_fixer.rb
Metrics/ClassLength:
  Exclude:
    - lib/tufts/hostname_fixer.rb
Metrics/MethodLength:
  Exclude:
    - app/controllers/omniauthcallbacks_controller.rb
    - app/controllers/tufts/tdl_resources_controller.rb
    - app/models/tufts/iiif_manifest.rb
    - lib/tufts/hostname_fixer.rb
Naming/MethodParameterName:
  Exclude:
    - lib/in_menu_behavior/helper.rb
Lint/Debugger:
  Exclude:
    - lib/tufts/hostname_fixer.rb
Style/SymbolArray:
  StyleGuide: '#brackets'
Style/Documentation:
  Exclude:
    - app/**/*
    - test/*
    - app/models/user.rb
    - lib/**/*
    - spec/**/*
    - config/**/*
Lint/UnusedMethodArgument:
  Exclude:
    - app/controllers/application_controller.rb
Layout/LineLength:
  Exclude:
    - config/**/*
Rails/ApplicationRecord:
  Exclude:
    - app/models/spotlight/*
Rails/FilePath:
  Exclude:
    - lib/tasks/test.rake
Rails/Output:
  Exclude:
      - lib/tufts/hostname_fixer.rb
RSpec/ExampleLength:
  Exclude:
    - spec/features/feature_page_customizations_spec.rb
    - spec/features/sir_trevor_customizations_spec.rb
    - spec/features/tdl_ingest_spec.rb
    - spec/features/view_customizations_spec.rb
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - stage
